version: "3.3"
 
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "443:443/tcp"
      - "80:80/tcp"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: "admin" #changeme
    # Volumes for persistent storage.
    volumes:
      - ./data:/etc/pihole/
      - ./data/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
    # This is some text data by Ian
    # Here is text from GitHub this is another update
